### ISSUE TITLE
Manifest unknown when trying to pull ghcr.io/ietf-tools/www:v2.0.0

### ISSUE THREAD

**Issue by microamp** [ietf-tools/www#392]
In `helm/values.yaml`, we currently have

```yaml
wagtail:
  name: wagtail
  image:
    repository: "ghcr.io/ietf-tools/www"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v2.0.0"
```

But when I run
```sh
docker pull ghcr.io/ietf-tools/www:v2.0.0
```
I'm getting
```text
Error response from daemon: manifest unknown
```

It's because we have recently renamed the repo and image name from `wagtail_website` to `www`  (https://github.com/ietf-tools/www/pull/387), and `www:v2.0.0` doesn't exist as the tag had been published before the image was renamed.

Using a newer tag should work.
```sh
docker pull ghcr.io/ietf-tools/www:v2.1.3
```
```text
v2.1.3: Pulling from ietf-tools/www
Digest: sha256:408b28037f059f49a85209f3903fccac5bcdb503e81cd597c30bff93151490d8
Status: Image is up to date for ghcr.io/ietf-tools/www:v2.1.3
ghcr.io/ietf-tools/www:v2.1.3
```
